# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('swagger', models.CharField(max_length=45)),
                ('base_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('terms_of_service', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=255)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='swagger.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('at', models.CharField(max_length=45)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(max_length=45)),
                ('required', models.BooleanField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=45)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Document')),
            ],
        ),
        migrations.CreateModel(
            name='PathParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Parameter')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Path')),
            ],
        ),
        migrations.CreateModel(
            name='PathSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField(null=True)),
                ('required', models.BooleanField()),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Path')),
            ],
        ),
        migrations.CreateModel(
            name='PathTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Path')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('example', models.CharField(max_length=45, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swagger.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('at', models.CharField(max_length=45)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='swagger.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Document')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swagger.Schema'),
        ),
        migrations.AddField(
            model_name='pathtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Tag'),
        ),
        migrations.AddField(
            model_name='pathschema',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Schema'),
        ),
    ]
