# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('swagger', models.CharField(default='2.0', max_length=45)),
                ('base_path', models.CharField(max_length=255)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('at', models.CharField(choices=[('path', 'path'), ('body', 'body')], default='body', max_length=45)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=45)),
                ('required', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('post', 'post'), ('get', 'get'), ('delete', 'delete'), ('put', 'put')], default='get', max_length=45)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PathParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Parameter')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Path')),
            ],
        ),
        migrations.CreateModel(
            name='PathSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.CharField(choices=[('path', 'path'), ('body', 'body')], default='body', max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField(blank=True, null=True)),
                ('required', models.BooleanField()),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Path')),
            ],
        ),
        migrations.CreateModel(
            name='PathTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Path')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('type', models.CharField(choices=[('string', 'string'), ('integer', 'integer'), ('object', 'object'), ('array', 'array')], default='string', max_length=45)),
                ('required', models.BooleanField(default=False)),
                ('example', models.CharField(blank=True, max_length=45, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swagger.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_code', models.IntegerField(choices=[(200, 200), (202, 202), (400, 400), (401, 401), (403, 403), (404, 404)], default=200)),
                ('description', models.CharField(max_length=255)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Path')),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('type', models.CharField(choices=[('string', 'string'), ('integer', 'integer'), ('object', 'object'), ('array', 'array')], default='string', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=45)),
                ('type', models.CharField(default='apiKey', max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('at', models.CharField(default='header', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='swagger.Document')),
                ('version', models.CharField(default='1.0.0', max_length=45)),
                ('title', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('terms_of_service', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swagger.Document'),
        ),
        migrations.AddField(
            model_name='security',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Document'),
        ),
        migrations.AddField(
            model_name='schema',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Document'),
        ),
        migrations.AddField(
            model_name='response',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Schema'),
        ),
        migrations.AddField(
            model_name='property',
            name='schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swagger.Schema'),
        ),
        migrations.AddField(
            model_name='pathtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Tag'),
        ),
        migrations.AddField(
            model_name='pathschema',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Schema'),
        ),
        migrations.AddField(
            model_name='path',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Document'),
        ),
        migrations.AddField(
            model_name='path',
            name='parameters',
            field=models.ManyToManyField(related_name='paths', through='swagger.PathParameter', to='swagger.Parameter'),
        ),
        migrations.AddField(
            model_name='path',
            name='schemas',
            field=models.ManyToManyField(related_name='paths', through='swagger.PathSchema', to='swagger.Schema'),
        ),
        migrations.AddField(
            model_name='path',
            name='tags',
            field=models.ManyToManyField(related_name='paths', through='swagger.PathTag', to='swagger.Tag'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Document'),
        ),
    ]
