# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swagger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_code', models.IntegerField(choices=[(200, 200), (202, 202)], default=200)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='path',
            name='parameters',
            field=models.ManyToManyField(related_name='paths', through='swagger.PathParameter', to='swagger.Parameter'),
        ),
        migrations.AddField(
            model_name='path',
            name='schemas',
            field=models.ManyToManyField(related_name='paths', through='swagger.PathSchema', to='swagger.Schema'),
        ),
        migrations.AlterField(
            model_name='document',
            name='swagger',
            field=models.CharField(default='2.0', max_length=45),
        ),
        migrations.AlterField(
            model_name='info',
            name='version',
            field=models.CharField(default='1.0.0', max_length=45),
        ),
        migrations.AlterField(
            model_name='path',
            name='method',
            field=models.CharField(choices=[('post', 'post'), ('get', 'get'), ('delete', 'delete'), ('put', 'put')], default='get', max_length=45),
        ),
        migrations.AlterField(
            model_name='security',
            name='type',
            field=models.CharField(choices=[('string', 'string'), ('integer', 'integer')], default='string', max_length=45),
        ),
        migrations.AddField(
            model_name='response',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Path'),
        ),
        migrations.AddField(
            model_name='response',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swagger.Schema'),
        ),
    ]
