# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swagger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='terms_of_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
