# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-21 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swagger', '0002_auto_20170608_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_for', to='swagger.Schema'),
        ),
        migrations.AlterField(
            model_name='security',
            name='name',
            field=models.CharField(default='Authorization', max_length=45),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
