# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swagger', '0002_auto_20170608_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='at',
            field=models.CharField(choices=[('path', 'path'), ('body', 'body')], default='body', max_length=45),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathschema',
            name='at',
            field=models.CharField(choices=[('path', 'path'), ('body', 'body')], default='body', max_length=45),
        ),
        migrations.AlterField(
            model_name='pathschema',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='example',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swagger.Property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swagger.Schema'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('string', 'string'), ('integer', 'integer')], default='string', max_length=45),
        ),
        migrations.AlterField(
            model_name='response',
            name='http_code',
            field=models.IntegerField(choices=[(200, 200), (202, 202), (400, 400), (401, 401), (403, 403), (404, 404)], default=200),
        ),
        migrations.AlterField(
            model_name='schema',
            name='type',
            field=models.CharField(choices=[('string', 'string'), ('integer', 'integer')], default='string', max_length=45),
        ),
    ]
