# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swagger', '0003_auto_20170608_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='swagger.Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('string', 'string'), ('integer', 'integer'), ('object', 'object'), ('array', 'array')], default='string', max_length=45),
        ),
        migrations.AlterField(
            model_name='schema',
            name='type',
            field=models.CharField(choices=[('string', 'string'), ('integer', 'integer'), ('object', 'object'), ('array', 'array')], default='string', max_length=45),
        ),
        migrations.AlterField(
            model_name='security',
            name='type',
            field=models.CharField(choices=[('string', 'string'), ('integer', 'integer'), ('object', 'object'), ('array', 'array')], default='string', max_length=45),
        ),
    ]
