# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swagger', '0004_auto_20170608_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='id',
        ),
        migrations.RemoveField(
            model_name='security',
            name='id',
        ),
        migrations.AlterField(
            model_name='info',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='swagger.Document'),
        ),
        migrations.AlterField(
            model_name='security',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='swagger.Document'),
        ),
    ]
