# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swagger', '0005_auto_20170608_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
