# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-22 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swagger', '0005_auto_20180322_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(default=None, max_length=1080),
        ),
    ]
