# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-22 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swagger', '0006_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=1080, null=True),
        ),
    ]
