#
# syntax: https://docs.docker.com/compose/yml/
#

version: "2"

services:
    swagger_ui:
        image: cuongnb14/swagger_ui:0.1
        build: .
        networks:
            - swagger-back
        expose:
            - "8000"
        ports:
            - "8000:8000"
        volumes:
            - .:/usr/src/app
        env_file: docker-env
        environment:
            DJANGO_SETTINGS_MODULE: 'config.settings.local'
        cpu_shares: 512             # 0.5 CPU
        mem_limit: 1036870912        # 1 G RAM
        # restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "100M"
                max-file: "3"
        # command: /usr/local/bin/gunicorn config.wsgi:application -w 2 -b :8000
        command: python3 manage.py runserver 0.0.0.0:8000

    mariadb:
        image: mariadb:10.3
        command: --slow_query_log='ON' --long_query_time=0.5 --slow_query_log_file='/var/lib/mysql/slow-queries.log'
        volumes:
            - ./mysql-data/:/var/lib/mysql/
            - ./mysql-init-data/:/docker-entrypoint-initdb.d/
      #        env_file:
      #            - ./docker-env
        environment:
           - MYSQL_ROOT_PASSWORD=lab@secret
           - MYSQL_USER=swagger
           - MYSQL_PASSWORD=lab@123
        ports:
            - "127.0.0.1:3309:3306"
        networks:
            - swagger-back
        hostname: mysql
        logging:
            driver: "json-file"
            options:
                max-size: "100M"
                max-file: "3"
    docs:
        image: swaggerapi/swagger-ui:v3.4.5
        ports:
            - "8080:8080"
        environment:
            #- SWAGGER_JSON=/swagger.json
            - API_URL=http://swagger_ui/8000/docs/1?format=json
            - VALIDATOR_URL=null
        hostname: docs
        networks:
            - swagger-back
        logging:
            driver: "json-file"
            options:
                max-size: "100M"
                max-file: "3"

networks:
    swagger-back:

